// Sorthiya Damji Samaj - User Database
const users = [
    {
        id: 1,
        fullName: "Rajesh Kumar Sorthiya",
        gender: "male",
        age: 28,
        height: "5'8\"",
        weight: "70 kg",
        maritalStatus: "Never Married",
        religion: "Hindu",
        caste: "Sorthiya Damji",
        motherTongue: "Gujarati",
        nationality: "Indian",
        education: "B.Tech Computer Science",
        college: "IIT Mumbai",
        occupation: "Software Engineer",
        jobTitle: "Senior Software Engineer",
        company: "TCS",
        annualIncome: "8-10 Lakhs",
        fatherName: "Ramesh Kumar Sorthiya",
        fatherOccupation: "Business",
        motherName: "Sunita Sorthiya",
        motherOccupation: "Homemaker",
        siblings: "1 Sister",
        familyStatus: "Middle Class",
        familyLocation: "Mumbai, Maharashtra",
        diet: "Vegetarian",
        drinking: "No",
        smoking: "No",
        hobbies: "Reading, Traveling, Photography",
        fitness: "Regular Exercise",
        phone: "+91 98765 43210",
        email: "rajesh.kumar@email.com",
        currentAddress: "Andheri West, Mumbai",
        permanentAddress: "Borivali, Mumbai",
        location: "Mumbai, Maharashtra",
        preferredAgeRange: "24-30",
        preferredHeight: "5'2\" to 5'6\"",
        preferredEducation: "Graduate",
        preferredLocation: "Mumbai, Pune",
        partnerExpectations: "Looking for a caring and understanding partner",
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face"
    },
    {
        id: 2,
        fullName: "Priya Patel",
        gender: "female",
        age: 25,
        height: "5'4\"",
        weight: "55 kg",
        maritalStatus: "Never Married",
        religion: "Hindu",
        caste: "Sorthiya Damji",
        motherTongue: "Gujarati",
        nationality: "Indian",
        education: "M.A. English",
        college: "Gujarat University",
        occupation: "Teacher",
        jobTitle: "English Teacher",
        company: "Kendriya Vidyalaya",
        annualIncome: "4-5 Lakhs",
        fatherName: "Hitesh Patel",
        fatherOccupation: "Government Service",
        motherName: "Meena Patel",
        motherOccupation: "Homemaker",
        siblings: "1 Brother",
        familyStatus: "Middle Class",
        familyLocation: "Ahmedabad",
        diet: "Vegetarian",
        drinking: "No",
        smoking: "No",
        hobbies: "Dancing, Cooking, Reading",
        fitness: "Yoga",
        phone: "+91 98765 43211",
        email: "priya.patel@email.com",
        currentAddress: "Satellite, Ahmedabad",
        permanentAddress: "Maninagar, Ahmedabad",
        location: "Ahmedabad, Gujarat",
        preferredAgeRange: "26-32",
        preferredHeight: "5'6\" to 6'0\"",
        preferredEducation: "Graduate",
        preferredLocation: "Gujarat, Mumbai",
        partnerExpectations: "Looking for a respectful and family-oriented partner",
        profileImage: "https://images.unsplash.com/photo-1494790108755-2616b612b93e?w=300&h=300&fit=crop&crop=face"
    },
    {
        id: 3,
        fullName: "Amit Shah",
        gender: "male",
        age: 30,
        height: "5'10\"",
        weight: "75 kg",
        maritalStatus: "Never Married",
        religion: "Hindu",
        caste: "Sorthiya Damji",
        motherTongue: "Gujarati",
        nationality: "Indian",
        education: "MBA",
        college: "NMIMS Mumbai",
        occupation: "Business",
        jobTitle: "Business Owner",
        company: "Own Business",
        annualIncome: "15+ Lakhs",
        fatherName: "Jayesh Shah",
        fatherOccupation: "Business",
        motherName: "Kiran Shah",
        motherOccupation: "Homemaker",
        siblings: "No Siblings",
        familyStatus: "Upper Middle Class",
        familyLocation: "Surat",
        diet: "Vegetarian",
        drinking: "Occasionally",
        smoking: "No",
        hobbies: "Cricket, Business, Traveling",
        fitness: "Gym",
        phone: "+91 98765 43212",
        email: "amit.shah@email.com",
        currentAddress: "Adajan, Surat",
        permanentAddress: "Katargam, Surat",
        location: "Surat, Gujarat",
        preferredAgeRange: "24-28",
        preferredHeight: "5'2\" to 5'6\"",
        preferredEducation: "Graduate",
        preferredLocation: "Gujarat, Rajasthan",
        partnerExpectations: "Looking for a supportive and modern-thinking partner",
        profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=face"
    },
    {
        id: 4,
        fullName: "Neha Damji",
        gender: "female",
        age: 27,
        height: "5'3\"",
        weight: "52 kg",
        maritalStatus: "Never Married",
        religion: "Hindu",
        caste: "Sorthiya Damji",
        motherTongue: "Gujarati",
        nationality: "Indian",
        education: "BCA + MCA",
        college: "VIT Vellore",
        occupation: "Software Developer",
        jobTitle: "Full Stack Developer",
        company: "Infosys",
        annualIncome: "6-8 Lakhs",
        fatherName: "Suresh Damji",
        fatherOccupation: "CA",
        motherName: "Rekha Damji",
        motherOccupation: "Principal",
        siblings: "1 Sister, 1 Brother",
        familyStatus: "Upper Middle Class",
        familyLocation: "Rajkot",
        diet: "Vegetarian",
        drinking: "No",
        smoking: "No",
        hobbies: "Coding, Music, Painting",
        fitness: "Badminton",
        phone: "+91 98765 43213",
        email: "neha.damji@email.com",
        currentAddress: "Electronic City, Bangalore",
        permanentAddress: "Patel Colony, Rajkot",
        location: "Bangalore, Karnataka",
        preferredAgeRange: "28-34",
        preferredHeight: "5'7\" to 6'2\"",
        preferredEducation: "Engineering/IT preferred",
        preferredLocation: "Bangalore, Pune, Mumbai",
        partnerExpectations: "Looking for a career-focused partner who respects ambitions",
        profileImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop&crop=face"
    },
    {
        id: 5,
        fullName: "Vikash Sorthiya",
        gender: "male",
        age: 31,
        height: "6'0\"",
        weight: "80 kg",
        maritalStatus: "Never Married",
        religion: "Hindu",
        caste: "Sorthiya Damji",
        motherTongue: "Gujarati",
        nationality: "Indian",
        education: "MBBS, MD Pediatrics",
        college: "Grant Medical College, Mumbai",
        occupation: "Doctor",
        jobTitle: "Pediatrician",
        company: "Apollo Hospitals",
        annualIncome: "12-15 Lakhs",
        fatherName: "Dr. Mahesh Sorthiya",
        fatherOccupation: "Senior Doctor",
        motherName: "Dr. Savita Sorthiya",
        motherOccupation: "Gynecologist",
        siblings: "1 Brother (Doctor)",
        familyStatus: "Upper Middle Class",
        familyLocation: "Pune",
        diet: "Vegetarian",
        drinking: "No",
        smoking: "No",
        hobbies: "Reading, Tennis, Classical Music",
        fitness: "Tennis, Jogging",
        phone: "+91 98765 43214",
        email: "dr.vikash@email.com",
        currentAddress: "Baner, Pune",
        permanentAddress: "Kothrud, Pune",
        location: "Pune, Maharashtra",
        preferredAgeRange: "25-29",
        preferredHeight: "5'3\" to 5'7\"",
        preferredEducation: "Graduate, Medical preferred",
        preferredLocation: "Pune, Mumbai, Nashik",
        partnerExpectations: "Looking for an understanding partner who supports medical profession",
        profileImage: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&h=300&fit=crop&crop=face"
    },
    {
        id: 6,
        fullName: "Pooja Sorthiya",
        gender: "female",
        age: 26,
        height: "5'5\"",
        weight: "58 kg",
        maritalStatus: "Never Married",
        religion: "Hindu",
        caste: "Sorthiya Damji",
        motherTongue: "Gujarati",
        nationality: "Indian",
        education: "CA (Chartered Accountant)",
        college: "H.R. College, Mumbai",
        occupation: "Chartered Accountant",
        jobTitle: "Senior Auditor",
        company: "Deloitte",
        annualIncome: "10-12 Lakhs",
        fatherName: "Prakash Sorthiya",
        fatherOccupation: "Bank Manager",
        motherName: "Nisha Sorthiya",
        motherOccupation: "Teacher",
        siblings: "1 Brother (Engineer)",
        familyStatus: "Upper Middle Class",
        familyLocation: "Vadodara",
        diet: "Vegetarian",
        drinking: "No",
        smoking: "No",
        hobbies: "Finance, Traveling, Photography",
        fitness: "Dance, Gym",
        phone: "+91 98765 43215",
        email: "pooja.ca@email.com",
        currentAddress: "Andheri East, Mumbai",
        permanentAddress: "Shanti Nagar, Vadodara",
        location: "Mumbai, Maharashtra",
        preferredAgeRange: "28-35",
        preferredHeight: "5'8\" to 6'2\"",
        preferredEducation: "CA/MBA/Engineering preferred",
        preferredLocation: "Mumbai, Pune, Ahmedabad",
        partnerExpectations: "Looking for a financially stable, career-oriented partner",
        profileImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&crop=face"
    }
];

// Admin functions
const adminFunctions = {
    addUser: function(userData) {
        const newId = Math.max(...users.map(u => u.id)) + 1;
        const newUser = { ...userData, id: newId };
        users.push(newUser);
        return newUser;
    },
    
    editUser: function(userId, updatedData) {
        const userIndex = users.findIndex(u => u.id === userId);
        if (userIndex !== -1) {
            users[userIndex] = { ...users[userIndex], ...updatedData };
            return users[userIndex];
        }
        return null;
    },
    
    deleteUser: function(userId) {
        const userIndex = users.findIndex(u => u.id === userId);
        if (userIndex !== -1) {
            return users.splice(userIndex, 1)[0];
        }
        return null;
    },
    
    getAllUsers: function() {
        return users;
    }
};
